### ISSUE TITLE
use of internal package github.com/zekroTutorials/discordgo/internal/config not allowed

### ISSUE THREAD

**Issue by theboiiiiwhoisaboiii** [zekroTutorials/discordgo#1]
> Ich hab heute vor einer Stunde ca. angefangen ihre Videoreihe zu schauen und bin jetzt bei Folge 2 am Ende und finde es auch sehr gut, nur leider weiß ich nicht wie ich folgendes fixxen kann:

**`import (
        "fmt"
        "os"
        "os/signal"
        "syscall"
        "github.com/bwmarrin/discordgo"
        "github.com/zekroTutorials/discordgo/internal/config"
)`**

> wenn ich versuche die main.go Datei zu starten, kommt folgender error:

**`package command-line-arguments
        main.go:10:2: use of internal package github.com/zekroTutorials/discordgo/internal/config not allowed`**

> Könnten sie mir sagen wie ich das beheben kann?

**Comment by zekroTJA** [comment]
Wie ich es eigentlich im Tutorial schon gesagt habe muss natürlich der Package Name benutzt werden, welcher beim Initialisieren des go modules benutzt wurde. Also der name, der in der `go.mod` als `module` definiert ist. Als Beispiel könnte das für dich etwas wie `github.com/theboiiiiwhoisaboiii/discordgo` sein. Also wären die Imports dann bei dir z.B.:

```go
package main

import (
	"flag"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/bwmarrin/discordgo"
	"github.com/theboiiiiwhoisaboiii/discordgo/internal/commands"
	"github.com/theboiiiiwhoisaboiii/discordgo/internal/config"
	"github.com/theboiiiiwhoisaboiii/discordgo/internal/events"

       // ...
)
```
